/**
 * Utility functions for exporting documentation to various formats.
 * Extracted from doc-editor.tsx
 */

interface DocEntity {
    type: string;
    name: string;
    code: string;
    doc: string;
}

interface DocContent {
    summary: string;
    entities: DocEntity[];
}

export const downloadMarkdown = (fileName: string, fileLanguage: string, content: DocContent) => {
    let md = `# ${fileName}\n\n`;
    md += `**Language:** ${fileLanguage}\n`;
    md += `**Generated By:** DocuMint AI\n\n`;
    md += `## Summary\n\n${content.summary}\n\n`;
    md += `## Detailed Analysis\n\n`;

    if (content.entities) {
        content.entities.forEach(entity => {
            md += `### ${entity.name} (${entity.type})\n\n`;
            md += `${entity.doc}\n\n`;
            md += "```" + fileLanguage + "\n";
            md += entity.code + "\n";
            md += "```\n\n";
        });
    }

    const blob = new Blob([md], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${fileName}-docs.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
};

export const copyDocToClipboard = async (fileName: string, fileLanguage: string, content: DocContent): Promise<boolean> => {
    let text = `${fileName}\n${"=".repeat(fileName.length)}\n\n`;
    text += `Language: ${fileLanguage}\n`;
    text += `Generated by DocuMint AI\n\n`;
    text += `Summary\n-------\n${content.summary}\n\n`;

    if (content.entities) {
        content.entities.forEach(entity => {
            text += `${entity.name} (${entity.type})\n`;
            text += `-`.repeat(entity.name.length + entity.type.length + 3) + "\n";
            text += `${entity.doc}\n\n`;
        });
    }

    try {
        await navigator.clipboard.writeText(text);
        return true;
    } catch {
        return false;
    }
};

export const exportAsciiDoc = (fileName: string, fileLanguage: string, content: DocContent) => {
    try {
        let adoc = `= ${fileName}\n`;
        adoc += `:toc:\n:source-highlighter: highlight.js\n\n`;

        adoc += `*Language:* ${fileLanguage} +\n`;
        adoc += `*Generated By:* DocuMint AI\n\n`;

        adoc += `== Summary\n\n${content.summary || "No summary available."}\n\n`;
        adoc += `== Detailed Analysis\n\n`;

        if (content.entities && Array.isArray(content.entities)) {
            content.entities.forEach(entity => {
                adoc += `=== ${entity.name} (${entity.type})\n\n`;
                adoc += `${entity.doc || "No documentation."}\n\n`;
                adoc += `[source,${fileLanguage.toLowerCase()}]\n----\n`;
                adoc += (entity.code || "") + "\n";
                adoc += `----\n\n`;
            });
        }

        const blob = new Blob([adoc], { type: 'text/asciidoc' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `${fileName}-docs.adoc`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
        return true;
    } catch (e) {
        console.error("Export failed:", e);
        return false;
    }
};

export const exportRST = (fileName: string, fileLanguage: string, content: DocContent) => {
    try {
        const title = fileName;
        let rst = `${title}\n${"=".repeat(title.length)}\n\n`;

        rst += `**Language:** ${fileLanguage}\n\n`;
        rst += `**Generated By:** DocuMint AI\n\n`;

        rst += `Summary\n-------\n\n${content.summary || "No summary available."}\n\n`;
        rst += `Detailed Analysis\n-----------------\n\n`;

        if (content.entities && Array.isArray(content.entities)) {
            content.entities.forEach(entity => {
                const entityTitle = `${entity.name} (${entity.type})`;
                rst += `${entityTitle}\n${"^".repeat(entityTitle.length)}\n\n`;
                rst += `${entity.doc || "No documentation."}\n\n`;
                rst += `.. code-block:: ${fileLanguage.toLowerCase()}\n\n`;

                // Indent code for RST
                const indentedCode = (entity.code || "").split('\n').map(line => '    ' + line).join('\n');
                rst += `${indentedCode}\n\n`;
            });
        }

        const blob = new Blob([rst], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `${fileName}-docs.rst`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
        return true;
    } catch (e) {
        console.error("Export failed:", e);
        return false;
    }
};

export const exportHTML = (fileName: string, fileLanguage: string, content: DocContent) => {
    try {
        let html = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${fileName} - Documentation</title>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 800px; margin: 0 auto; padding: 40px 20px; line-height: 1.6; color: #333; }
        h1 { color: #1a1a1a; border-bottom: 2px solid #3b82f6; padding-bottom: 10px; }
        h2 { color: #374151; margin-top: 40px; }
        h3 { color: #3b82f6; }
        .meta { color: #6b7280; font-size: 14px; margin-bottom: 30px; }
        .entity { background: #f9fafb; border: 1px solid #e5e7eb; border-radius: 8px; padding: 20px; margin: 20px 0; }
        .entity-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 10px; }
        .entity-name { font-family: monospace; font-weight: bold; color: #3b82f6; }
        .entity-type { background: #e5e7eb; padding: 2px 8px; border-radius: 4px; font-size: 12px; text-transform: uppercase; }
        pre { background: #1f2937; color: #e5e7eb; padding: 15px; border-radius: 8px; overflow-x: auto; font-size: 13px; }
        .summary { background: #eff6ff; border-left: 4px solid #3b82f6; padding: 15px 20px; margin: 20px 0; }
    </style>
</head>
<body>
    <h1>${fileName}</h1>
    <div class="meta">
        <strong>Language:</strong> ${fileLanguage} | 
        <strong>Generated by:</strong> DocuMint AI
    </div>
    
    <h2>Summary</h2>
    <div class="summary">${content.summary}</div>
    
    <h2>Detailed Analysis</h2>`;

        if (content.entities) {
            content.entities.forEach(entity => {
                html += `
    <div class="entity">
        <div class="entity-header">
            <span class="entity-name">${entity.name}</span>
            <span class="entity-type">${entity.type.replace('_', ' ')}</span>
        </div>
        <p>${entity.doc}</p>
        <pre><code>${entity.code.replace(/</g, '&lt;').replace(/>/g, '&gt;')}</code></pre>
    </div>`;
            });
        }

        html += `
</body>
</html>`;

        const blob = new Blob([html], { type: 'text/html' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `${fileName}-docs.html`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
        return true;
    } catch (e) {
        console.error("Export failed:", e);
        return false;
    }
};
