import { notFound } from "next/navigation";
import { db } from "@/lib/db";
import Link from "next/link";
import { ArrowLeft, Share2, Shield, Calendar } from "lucide-react";
import { Metadata } from "next";

interface PublicDocProps {
    params: Promise<{ id: string }>;
}

export async function generateMetadata({ params }: PublicDocProps): Promise<Metadata> {
    const { id } = await params;
    const doc = await db.documentation.findFirst({
        where: { fileId: id, isPublic: true },
        include: { file: true }
    });

    if (!doc) {
        return { title: "Documentation Not Found" };
    }

    return {
        title: `${doc.file.name} - DocuMint AI`,
        description: `View public documentation for ${doc.file.name}, generated by DocuMint AI.`,
    };
}

export default async function PublicDocPage({ params }: PublicDocProps) {
    const { id } = await params;

    const doc = await db.documentation.findFirst({
        where: { fileId: id, isPublic: true },
        include: { file: true }
    });

    if (!doc) {
        notFound();
    }

    const content = JSON.parse(doc.content);

    return (
        <div className="min-h-screen bg-[#0A0A0B] text-white selection:bg-primary/30">
            {/* Header */}
            <header className="border-b border-white/5 bg-black/20 backdrop-blur-md sticky top-0 z-50">
                <div className="max-w-5xl mx-auto px-6 h-16 flex items-center justify-between">
                    <div className="flex items-center gap-4">
                        <Link href="/" className="font-bold text-white tracking-tight flex items-center gap-2 hover:opacity-80 transition-opacity">
                            <ArrowLeft className="w-4 h-4 text-muted-foreground" />
                            <span className="bg-gradient-to-r from-primary to-purple-400 bg-clip-text text-transparent">DocuMint AI</span>
                        </Link>
                    </div>
                    <div className="flex items-center gap-2 text-xs text-muted-foreground bg-white/5 px-3 py-1.5 rounded-full border border-white/5">
                        <Share2 className="w-3 h-3" />
                        Public Snapshot
                    </div>
                </div>
            </header>

            <main className="max-w-5xl mx-auto px-6 py-12 animate-fade-in">
                <div className="mb-12">
                    <div className="flex items-center gap-4 mb-4">
                        <h1 className="text-4xl md:text-5xl font-black tracking-tight text-white">{doc.file.name}</h1>
                        <span className="px-3 py-1 bg-white/10 text-white/70 text-sm rounded-lg uppercase font-bold tracking-wider">
                            {doc.file.language}
                        </span>
                    </div>

                    <div className="flex items-center gap-6 text-sm text-muted-foreground">
                        <div className="flex items-center gap-2">
                            <Calendar className="w-4 h-4" />
                            Generated {new Date(doc.createdAt).toLocaleDateString()}
                        </div>
                        {doc.metadata && (doc.metadata as any).qualityScore && (
                            <div className="flex items-center gap-2 text-emerald-400">
                                <Shield className="w-4 h-4" />
                                Quality Score: {(doc.metadata as any).qualityScore}/100
                            </div>
                        )}
                    </div>
                </div>

                {/* Summary */}
                <div className="glass-card bg-white/5 border-white/10 p-8 rounded-3xl mb-12 relative overflow-hidden">
                    <div className="absolute top-0 right-0 p-32 bg-primary/5 blur-[100px] rounded-full pointer-events-none" />
                    <h2 className="text-xl font-bold mb-4 flex items-center gap-2 text-white">
                        Project Summary
                    </h2>
                    <div className="prose prose-invert max-w-none text-white/80 leading-relaxed">
                        {content.summary}
                    </div>
                </div>

                {/* Detailed Analysis */}
                <div className="space-y-8">
                    <h2 className="text-2xl font-bold text-white mb-6">Detailed Analysis</h2>

                    {content.entities && content.entities.map((entity: any, i: number) => (
                        <div key={i} className="glass-card bg-black/40 border-white/5 p-6 rounded-2xl hover:border-white/10 transition-colors">
                            <div className="flex items-center justify-between mb-4">
                                <h3 className="text-lg font-bold text-primary font-mono">{entity.name}</h3>
                                <span className="text-[10px] uppercase font-bold tracking-widest bg-white/5 px-2 py-1 rounded text-muted-foreground">
                                    {entity.type}
                                </span>
                            </div>
                            <div className="prose prose-invert max-w-none text-sm text-gray-300 mb-6">
                                {entity.doc}
                            </div>
                            <div className="bg-[#1e1e1e] rounded-xl overflow-hidden border border-white/5">
                                <div className="px-4 py-2 border-b border-white/5 bg-white/5 text-[10px] font-mono text-muted-foreground uppercase tracking-wider">
                                    Source
                                </div>
                                <pre className="p-4 overflow-x-auto text-xs text-blue-200/80 font-mono scrollbar-thin scrollbar-thumb-white/10">
                                    <code>{entity.code}</code>
                                </pre>
                            </div>
                        </div>
                    ))}
                </div>

                <div className="mt-20 pt-10 border-t border-white/5 text-center">
                    <p className="text-muted-foreground mb-4">Documentation generated by</p>
                    <Link href="/" className="inline-flex items-center gap-2 px-6 py-3 bg-white/5 hover:bg-white/10 rounded-full text-white font-bold transition-all">
                        🚀 Try DocuMint AI for Free
                    </Link>
                </div>
            </main>
        </div>
    );
}
