"use client";

import { useState } from "react";
import { Download, FileText, FileCode, Archive, Loader2 } from "lucide-react";

interface BulkExportProps {
    fileIds: string[];
    onComplete?: () => void;
}

import { useToast } from "./toast";

export default function BulkExport({ fileIds, onComplete }: BulkExportProps) {
    const { toast } = useToast();
    const [isExporting, setIsExporting] = useState(false);
    const [format, setFormat] = useState<"md" | "html" | "json" | "pdf">("md");
    const [progress, setProgress] = useState(0);

    // Dynamic import for html2pdf client-side only
    const generatePDF = async (element: HTMLElement, filename: string) => {
        const html2pdf = (await import("html2pdf.js")).default;
        const opt: any = {
            margin: 1,
            filename: filename,
            image: { type: 'jpeg', quality: 0.98 },
            html2canvas: { scale: 2 },
            jsPDF: { unit: 'in', format: 'letter', orientation: 'portrait' }
        };
        return html2pdf().set(opt).from(element).save();
    };

    const handleExport = async () => {
        if (fileIds.length === 0) return;

        setIsExporting(true);
        setProgress(0);

        try {
            const docs: { name: string; content: string }[] = [];

            for (let i = 0; i < fileIds.length; i++) {
                const res = await fetch(`/api/docs/${fileIds[i]}`);
                if (res.ok) {
                    const data = await res.json();
                    docs.push({
                        name: data.file?.name || `file_${i}`,
                        content: data.documentation?.content || ""
                    });
                }
                setProgress(Math.round(((i + 1) / fileIds.length) * 100));
            }

            // Generate export file
            let exportContent = "";
            let filename = "";
            let mimeType = "";

            if (format === "md") {
                exportContent = docs.map(doc => {
                    try {
                        const parsed = JSON.parse(doc.content);
                        return `# ${doc.name}\n\n${parsed.summary || ""}\n\n---\n`;
                    } catch {
                        return `# ${doc.name}\n\n${doc.content}\n\n---\n`;
                    }
                }).join("\n");
                filename = "documentation-export.md";
                mimeType = "text/markdown";
            } else if (format === "html") {
                exportContent = `<!DOCTYPE html>
<html>
<head>
    <title>Documentation Export</title>
    <style>
        body { font-family: system-ui, sans-serif; max-width: 800px; margin: 40px auto; padding: 20px; }
        h1 { color: #1a1a1a; border-bottom: 2px solid #3b82f6; padding-bottom: 10px; }
        pre { background: #f4f4f5; padding: 16px; border-radius: 8px; overflow-x: auto; }
        hr { margin: 40px 0; border: none; border-top: 1px solid #e4e4e7; }
    </style>
</head>
<body>
${docs.map(doc => {
                    try {
                        const parsed = JSON.parse(doc.content);
                        return `<article><h1>${doc.name}</h1><p>${parsed.summary || ""}</p></article><hr>`;
                    } catch {
                        return `<article><h1>${doc.name}</h1><p>${doc.content}</p></article><hr>`;
                    }
                }).join("\n")}
</body>
</html>`;
                filename = "documentation-export.html";
                mimeType = "text/html";
            } else if (format === "pdf") {
                // For PDF, we construct HTML then convert
                const pdfContent = `
                    <div id="pdf-content" style="font-family: sans-serif; padding: 20px;">
                        <h1 style="text-align: center; border-bottom: 2px solid #333; padding-bottom: 10px;">Documentation Export</h1>
                        <p style="text-align: center; color: #666; margin-bottom: 40px;">Generated by DocuMint AI - ${new Date().toLocaleDateString()}</p>
                        ${docs.map(doc => {
                    try {
                        const parsed = JSON.parse(doc.content);
                        return `
                                    <div style="page-break-after: always; margin-top: 30px;">
                                        <h2 style="color: #2563eb;">${doc.name}</h2>
                                        <div style="background: #f3f4f6; padding: 15px; border-radius: 8px; margin-bottom: 20px;">
                                            <strong>Summary:</strong><br/>
                                            ${parsed.summary || "No summary"}
                                        </div>
                                        ${parsed.entities ? parsed.entities.map((e: any) => `
                                            <div style="margin-bottom: 20px; border: 1px solid #e5e7eb; padding: 10px; border-radius: 6px;">
                                                <h3 style="margin: 0 0 10px 0; font-size: 16px;">${e.name} <span style="font-size: 12px; background: #e5e7eb; padding: 2px 6px; border-radius: 4px;">${e.type}</span></h3>
                                                <p style="font-size: 14px; margin: 0;">${e.doc}</p>
                                            </div>
                                        `).join('') : ''}
                                    </div>
                                `;
                    } catch {
                        return `<div style="page-break-after: always;"><h2>${doc.name}</h2><pre>${doc.content}</pre></div>`;
                    }
                }).join("")}
                    </div>
                 `;

                // Create a temporary container
                const container = document.createElement('div');
                container.innerHTML = pdfContent;
                document.body.appendChild(container);

                await generatePDF(container, "documint-export.pdf");

                document.body.removeChild(container);
                onComplete?.();
                setIsExporting(false);
                return; // PDF handles its own download
            } else {
                exportContent = JSON.stringify(docs.map(doc => {
                    try {
                        return { name: doc.name, ...JSON.parse(doc.content) };
                    } catch {
                        return { name: doc.name, content: doc.content };
                    }
                }), null, 2);
                filename = "documentation-export.json";
                mimeType = "application/json";
            }

            // Download file
            const blob = new Blob([exportContent], { type: mimeType });
            const url = URL.createObjectURL(blob);
            const a = document.createElement("a");
            a.href = url;
            a.download = filename;
            document.body.appendChild(a);
            a.click();
            document.body.removeChild(a);
            URL.revokeObjectURL(url);

            onComplete?.();
        } catch (error) {
            console.error("Export error:", error);
            toast("Export failed", "error");
        } finally {
            setIsExporting(false);
        }
    };

    if (fileIds.length === 0) {
        return null;
    }

    return (
        <div className="fixed bottom-20 right-4 bg-white rounded-xl shadow-lg border p-4 z-40 animate-in slide-in-from-bottom-4">
            <div className="flex items-center gap-3 mb-3">
                <Archive className="w-5 h-5 text-blue-600" />
                <span className="font-medium text-zinc-100">
                    {fileIds.length} file{fileIds.length > 1 ? "s" : ""} selected
                </span>
            </div>

            <div className="flex gap-2 mb-3">
                {[
                    { value: "md" as const, icon: FileText, label: "Markdown" },
                    { value: "html" as const, icon: FileCode, label: "HTML" },
                    { value: "json" as const, icon: FileCode, label: "JSON" },
                    { value: "pdf" as const, icon: FileText, label: "PDF" },
                ].map(({ value, icon: Icon, label }) => (
                    <button
                        key={value}
                        onClick={() => setFormat(value)}
                        className={`flex items-center gap-1 px-3 py-1.5 rounded-lg text-sm transition-colors ${format === value
                            ? "bg-blue-100 text-blue-700 border border-blue-200"
                            : "bg-gray-100 text-gray-600 hover:bg-gray-200"
                            }`}
                    >
                        <Icon className="w-3 h-3" />
                        {label}
                    </button>
                ))}
            </div>

            {isExporting ? (
                <div className="space-y-2">
                    <div className="flex items-center gap-2 text-sm text-gray-600">
                        <Loader2 className="w-4 h-4 animate-spin" />
                        Exporting... {progress}%
                    </div>
                    <div className="w-full bg-gray-200 rounded-full h-2">
                        <div
                            className="bg-blue-600 h-2 rounded-full transition-all"
                            style={{ width: `${progress}%` }}
                        />
                    </div>
                </div>
            ) : (
                <button
                    onClick={handleExport}
                    className="w-full flex items-center justify-center gap-2 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors"
                >
                    <Download className="w-4 h-4" />
                    Export All
                </button>
            )}
        </div>
    );
}
