import { NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { db } from "@/lib/db";
import { safeJsonParse } from "@/lib/utils";

export async function POST(req: Request) {
    try {
        const session = await getServerSession(authOptions);
        if (!session?.user?.id) {
            return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
        }

        const body = await req.json();
        const { fileId, repoFullName } = body;

        if (!fileId || !repoFullName) {
            return NextResponse.json({ error: "Missing required fields" }, { status: 400 });
        }

        // 1. Get GitHub Token
        const connection = await db.gitHubConnection.findUnique({
            where: { userId: session.user.id }
        });

        if (!connection?.accessToken) {
            return NextResponse.json({ error: "GitHub not connected" }, { status: 400 });
        }

        const token = connection.accessToken;

        // 2. Fetch File and Documentation
        const file = await db.file.findUnique({
            where: { id: fileId },
            include: { documentation: true }
        });

        if (!file || !file.documentation) {
            return NextResponse.json({ error: "File or documentation not found" }, { status: 404 });
        }

        // 3. Generate Markdown Content
        const docContent = safeJsonParse(file.documentation.content, {} as any);
        let md = `# ${file.name}\n\n`;
        md += `**Language:** ${file.language}\n`;
        md += `**Generated By:** DocuMint AI\n\n`;
        md += `## Summary\n\n${docContent.summary}\n\n`;
        md += `## Detailed Analysis\n\n`;
        if (docContent.entities) {
            // @ts-ignore
            docContent.entities.forEach(entity => {
                md += `### ${entity.name} (${entity.type})\n\n`;
                md += `${entity.doc}\n\n`;
                md += "```" + file.language + "\n";
                md += entity.code + "\n";
                md += "```\n\n";
            });
        }

        const filePath = `docs/${file.name}.md`;
        const branchName = `documint-${file.name.replace(/\./g, '-')}-${Date.now()}`;

        const headers = {
            "Authorization": `Bearer ${token}`,
            "Accept": "application/vnd.github.v3+json",
            "Content-Type": "application/json"
        };

        // 4. Get Default Branch (and its SHA)
        const repoRes = await fetch(`https://api.github.com/repos/${repoFullName}`, { headers });
        if (!repoRes.ok) throw new Error("Failed to fetch repo info");
        const repoData = await repoRes.json();
        const defaultBranch = repoData.default_branch;

        const refRes = await fetch(`https://api.github.com/repos/${repoFullName}/git/ref/heads/${defaultBranch}`, { headers });
        if (!refRes.ok) throw new Error("Failed to fetch default branch ref");
        const refData = await refRes.json();
        const baseSha = refData.object.sha;

        // 5. Create New Branch
        const createBranchRes = await fetch(`https://api.github.com/repos/${repoFullName}/git/refs`, {
            method: "POST",
            headers,
            body: JSON.stringify({
                ref: `refs/heads/${branchName}`,
                sha: baseSha
            })
        });
        if (!createBranchRes.ok) throw new Error("Failed to create branch");

        // 6. Create File (Commit)
        const fileContentEncoded = Buffer.from(md).toString('base64');
        const createFileRes = await fetch(`https://api.github.com/repos/${repoFullName}/contents/${filePath}`, {
            method: "PUT",
            headers,
            body: JSON.stringify({
                message: `Add documentation for ${file.name}`,
                content: fileContentEncoded,
                branch: branchName
            })
        });

        if (!createFileRes.ok) {
            // Handle case where file exists? For now assume valid new file path or overwrite
            const err = await createFileRes.json();
            throw new Error(`Failed to create file: ${err.message}`);
        }

        // 7. Create Pull Request
        const prRes = await fetch(`https://api.github.com/repos/${repoFullName}/pulls`, {
            method: "POST",
            headers,
            body: JSON.stringify({
                title: `Docs: ${file.name}`,
                body: `Auto-generated documentation for ${file.name} by DocuMint AI.`,
                head: branchName,
                base: defaultBranch
            })
        });

        if (!prRes.ok) throw new Error("Failed to create PR");
        const prData = await prRes.json();

        return NextResponse.json({
            success: true,
            prUrl: prData.html_url
        });

    } catch (error: any) {
        console.error("Create PR error:", error);
        return NextResponse.json({ error: error.message || "Internal Server Error" }, { status: 500 });
    }
}
