import { NextRequest, NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { z } from "zod";
import { authOptions } from "@/lib/auth";
import { db } from "@/lib/db";
import { safeJsonParse } from "@/lib/utils";
import { enforceRateLimit } from "@/lib/rate-limit";
import { errorResponse, validateBody, ApiErrors } from "@/lib/api-utils";
import { decrypt } from "@/lib/security/encryption";

const createPrSchema = z.object({
    fileId: z.string().trim().min(1).max(100),
    repoFullName: z.string().trim().min(3).max(200),
}).strict();

interface DocEntity {
    name: string;
    type: string;
    doc: string;
    code: string;
}

interface DocContent {
    summary: string;
    entities?: DocEntity[];
}

/**
 * POST /api/github/pr
 * Generates markdown documentation and creates a GitHub Pull Request with the file.
 */
export async function POST(req: NextRequest) {
    try {
        const session = await getServerSession(authOptions);
        if (!session?.user?.id) {
            throw ApiErrors.unauthorized();
        }

        // 1. Enforce Rate Limit
        await enforceRateLimit(session.user.id, "pro");

        // 2. Validate Body
        const { fileId, repoFullName } = await validateBody(req, createPrSchema);

        // 3. Get GitHub Token and Decrypt
        const connection = await db.gitHubConnection.findUnique({
            where: { userId: session.user.id }
        });

        if (!connection || !connection.accessToken) {
            throw ApiErrors.badRequest("GitHub account not connected.");
        }

        let decryptedToken: string;
        try {
            decryptedToken = decrypt(connection.accessToken);
        } catch {
            throw ApiErrors.internalError("Failed to access GitHub credentials.");
        }

        // 4. Fetch File and Documentation
        const file = await db.file.findUnique({
            where: { id: fileId },
            include: { documentation: true }
        });

        if (!file || !file.documentation) {
            throw ApiErrors.notFound("Documentation");
        }

        // Check permissions (User must own or have access to file)
        const { checkFilePermission } = await import("@/lib/permissions");
        const hasPermission = await checkFilePermission(session.user.id, fileId, "view");
        if (!hasPermission) {
            throw ApiErrors.forbidden("You do not have permission to export this file.");
        }

        // 5. Generate Markdown Content
        const docContent = safeJsonParse<DocContent>(file.documentation.content, { summary: "" });
        let md = `# ${file.name}\n\n`;
        md += `**Language:** ${file.language}\n`;
        md += `**Generated By:** DocuMint AI\n\n`;
        md += `## Summary\n\n${docContent.summary}\n\n`;
        md += `## Detailed Analysis\n\n`;
        if (docContent.entities) {
            docContent.entities.forEach(entity => {
                md += `### ${entity.name} (${entity.type})\n\n`;
                md += `${entity.doc}\n\n`;
                md += "```" + file.language + "\n";
                md += entity.code + "\n";
                md += "```\n\n";
            });
        }

        const filePath = `docs/${file.name}.md`;
        const branchName = `documint-${file.name.replace(/\./g, '-')}-${Date.now()}`;

        const headers = {
            "Authorization": `Bearer ${decryptedToken}`,
            "Accept": "application/vnd.github.v3+json",
            "Content-Type": "application/json"
        };

        // 6. Get Default Branch via GitHub API
        const repoRes = await fetch(`https://api.github.com/repos/${repoFullName}`, { headers });
        if (!repoRes.ok) {
            const errData = await repoRes.json().catch(() => ({}));
            throw new Error(`Failed to fetch repo info: ${errData.message || repoRes.statusText}`);
        }
        const repoData = await repoRes.json();
        const defaultBranch = repoData.default_branch;

        // 7. Get Base SHA
        const refRes = await fetch(`https://api.github.com/repos/${repoFullName}/git/ref/heads/${defaultBranch}`, { headers });
        if (!refRes.ok) throw new Error("Failed to fetch default branch ref from GitHub.");
        const refData = await refRes.json();
        const baseSha = refData.object.sha;

        // 8. Create New Branch
        const createBranchRes = await fetch(`https://api.github.com/repos/${repoFullName}/git/refs`, {
            method: "POST",
            headers,
            body: JSON.stringify({
                ref: `refs/heads/${branchName}`,
                sha: baseSha
            })
        });
        if (!createBranchRes.ok) {
            const errData = await createBranchRes.json().catch(() => ({}));
            throw new Error(`Failed to create branch: ${errData.message || createBranchRes.statusText}`);
        }

        // 9. Create File (Commit)
        const fileContentEncoded = Buffer.from(md).toString('base64');
        const createFileRes = await fetch(`https://api.github.com/repos/${repoFullName}/contents/${filePath}`, {
            method: "PUT",
            headers,
            body: JSON.stringify({
                message: `Add documentation for ${file.name}`,
                content: fileContentEncoded,
                branch: branchName
            })
        });

        if (!createFileRes.ok) {
            const errData = await createFileRes.json().catch(() => ({}));
            throw new Error(`Failed to commit file: ${errData.message || createFileRes.statusText}`);
        }

        // 10. Create Pull Request
        const prRes = await fetch(`https://api.github.com/repos/${repoFullName}/pulls`, {
            method: "POST",
            headers,
            body: JSON.stringify({
                title: `Docs: ${file.name}`,
                body: `Auto-generated documentation for ${file.name} by DocuMint AI.`,
                head: branchName,
                base: defaultBranch
            })
        });

        if (!prRes.ok) {
            const errData = await prRes.json().catch(() => ({}));
            throw new Error(`Failed to create PR on GitHub: ${errData.message || prRes.statusText}`);
        }
        const prData = await prRes.json();

        // 11. Audit Logging
        try {
            const { logAudit } = await import("@/lib/audit-logger");
            await logAudit({
                userId: session.user.id,
                action: "EXPORT_GITHUB_PR",
                entity: "Documentation",
                entityId: fileId,
                details: { 
                    repoFullName, 
                    fileName: file.name,
                    branch: branchName,
                    prUrl: prData.html_url
                }
            });
        } catch {
            // Non-blocking
        }

        return NextResponse.json({
            success: true,
            prUrl: prData.html_url
        }, { status: 201 });

    } catch (error) {
        return errorResponse(error);
    }
}
